-- MySQL Script generated by MySQL Workbench
-- Mon Jan 22 10:30:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
USE `google_drive` ;
drop database `google_drive`;
-- -----------------------------------------------------
-- Table `google_drive`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `google_drive`.`usuario` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `espaco` DOUBLE DEFAULT 100,
  `password` TEXT NULL,
  `email` VARCHAR(50) UNIQUE NOT NULL,
  `avatar` TEXT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- DROP TABLE usuario;

CREATE TABLE IF NOT EXISTS `google_drive`.`arquivo` (
  `id` INT NULL AUTO_INCREMENT,
  `nome_ficheiro` TEXT NOT NULL,
  `ficheiro` LONGBLOB NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  CONSTRAINT `fk_arquivos_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `google_drive`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- drop table arquivo;

ALTER TABLE `arquivo` ADD `tamanho` DOUBLE;

-- -----------------------------------------------------
-- Table `google_drive`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id` INT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(500) NULL,
  `arquivo_id` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comentarios_arquivos1`
    FOREIGN KEY (`arquivo_id`)
    REFERENCES `arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- DROP TABLE `comentarios`;

-- -----------------------------------------------------
-- Table `google_drive`.`respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `google_drive`.`respostas` (
  `id` INT NULL AUTO_INCREMENT,
  `conteudo` TEXT NULL,
  `comentarios_id` INT NOT NULL,
  `email` VARCHAR(50),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_respostas_comentarios1`
    FOREIGN KEY (`comentarios_id`)
    REFERENCES `google_drive`.`comentarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- DROP TABLE `respostas`;

-- -----------------------------------------------------
-- Table `google_drive`.`compartilhados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compartilhados` (
  `id` INT AUTO_INCREMENT,
  `usuario_id` INT,
  `arquivo_id` INT,
  `email_amigo` VARCHAR(50),
  PRIMARY KEY (`id`, `usuario_id`, `arquivo_id`),
  CONSTRAINT `fk_compartilhados_usuario1`
    FOREIGN KEY (`arquivo_id`, `usuario_id`)
    REFERENCES `arquivo` (`id`,`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- drop table `compartilhados`;

